#include <fixedwide/all.hpp>
#include <bit>
#include <cstdint>
#include <iostream>
#include <random>
#include <string_view>
using namespace fixedwide;
template<class F>F rv(std::mt19937_64&g){if constexpr(F::bits==8)return F::from_raw(std::bit_cast<int8_t>(uint8_t(g())));else if constexpr(F::bits==16)return F::from_raw(std::bit_cast<int16_t>(uint16_t(g())));else if constexpr(F::bits==32)return F::from_raw(std::bit_cast<int32_t>(uint32_t(g())));else if constexpr(F::bits==64)return F::from_raw(std::bit_cast<int64_t>(g()));else if constexpr(F::bits==128)return F::from_raw(wide::int128(g(),g()));else return F::from_raw(wide::int256(g(),g(),g(),g()));}
template<class F>void run(const char*name,uint64_t n,uint64_t seed,uint64_t&checks,uint64_t&fails){std::mt19937_64 g(seed);auto one=[&](F x){char buf[256];auto z=to_chars(buf,sizeof buf,x);++checks;if(!z){++fails;if(fails<20)std::cerr<<"format failure "<<name<<" err="<<int(z.error())<<'\n';return;}auto p=parse<F>(std::string_view(buf,*z));++checks;if(!p||*p!=x){++fails;if(fails<20)std::cerr<<"roundtrip failure "<<name<<" text="<<std::string_view(buf,*z)<<" parse="<<(p?"value":"error")<<'\n';}auto le=to_bytes<endian::little>(x);auto ple=from_bytes<F,endian::little>(le);++checks;if(!ple||*ple!=x){++fails;if(fails<20)std::cerr<<"LE binary failure "<<name<<'\n';}auto be=to_bytes<endian::big>(x);auto pbe=from_bytes<F,endian::big>(be);++checks;if(!pbe||*pbe!=x){++fails;if(fails<20)std::cerr<<"BE binary failure "<<name<<'\n';}uint8_t raw[80]{};store_unaligned<endian::little>(raw+3,x);auto u=load_unaligned<F,endian::little>(raw+3);++checks;if(u!=x){++fails;if(fails<20)std::cerr<<"unaligned failure "<<name<<'\n';}};one(F{});one(F::min());one(F::max());for(uint64_t i=0;i<n;++i)one(rv<F>(g));std::cout<<name<<" cases="<<(n+3)<<'\n';}
int main(){uint64_t c=0,f=0;run<Fixed8<2>>("Fixed8<2>",10000,1,c,f);run<Fixed16<4>>("Fixed16<4>",10000,2,c,f);run<Fixed32<9>>("Fixed32<9>",15000,3,c,f);run<Fixed64<12>>("Fixed64<12>",15000,4,c,f);run<Fixed128<12>>("Fixed128<12>",10000,5,c,f);run<Fixed128<38>>("Fixed128<38>",5000,6,c,f);run<Fixed256<18>>("Fixed256<18>",3000,7,c,f);run<Fixed256<76>>("Fixed256<76>",1500,8,c,f);std::cout<<"checks="<<c<<" failures="<<f<<'\n';return f?1:0;}
