#include <fixedwide/all.hpp>
#include <boost/multiprecision/cpp_int.hpp>
#include <bit>
#include <cstdint>
#include <iostream>
#include <random>
using namespace fixedwide;
using boost::multiprecision::cpp_int;

static cpp_int p10(unsigned d){cpp_int x=1;while(d--)x*=10;return x;}
template<class F> cpp_int cv(F f){if constexpr(F::bits<=64)return cpp_int(f.raw());else if constexpr(F::bits==128){auto r=f.raw();cpp_int x=(cpp_int(r.high)<<64)|r.low;if(r.high>>63)x-=(cpp_int(1)<<128);return x;}else{auto r=f.raw();cpp_int x=0;for(int i=3;i>=0;--i)x=(x<<64)|r.limbs[i];if(r.limbs[3]>>63)x-=(cpp_int(1)<<256);return x;}}
template<class F> F randv(std::mt19937_64&g){if constexpr(F::bits==8)return F::from_raw(std::bit_cast<int8_t>(uint8_t(g())));else if constexpr(F::bits==16)return F::from_raw(std::bit_cast<int16_t>(uint16_t(g())));else if constexpr(F::bits==32)return F::from_raw(std::bit_cast<int32_t>(uint32_t(g())));else if constexpr(F::bits==64)return F::from_raw(std::bit_cast<int64_t>(g()));else if constexpr(F::bits==128)return F::from_raw(wide::int128(g(),g()));else return F::from_raw(wide::int256(g(),g(),g(),g()));}
template<class F> F raw1(int v){if constexpr(F::bits<=64)return F::from_raw(static_cast<typename F::raw_type>(v));else if constexpr(F::bits==128)return F::from_raw(wide::int128(v));else return F::from_raw(wide::int256(v));}
struct O{bool ok;cpp_int v;ArithmeticError e;};
static cpp_int lo(unsigned b){return -(cpp_int(1)<<(b-1));} static cpp_int hi(unsigned b){return (cpp_int(1)<<(b-1))-1;} static bool fits(cpp_int x,unsigned b){return x>=lo(b)&&x<=hi(b);}
static O rq(cpp_int n,cpp_int d,Rounding m,unsigned bits){if(d==0)return{false,0,ArithmeticError::division_by_zero};bool neg=(n<0)!=(d<0);if(n<0)n=-n;if(d<0)d=-d;cpp_int q=n/d,r=n%d;cpp_int lo0=-(cpp_int(1)<<(bits-1)),hi0=(cpp_int(1)<<(bits-1))-1,z0=neg?-q:q;if(z0<lo0||z0>hi0)return{false,0,ArithmeticError::overflow};if(r&&m==Rounding::exact)return{false,0,ArithmeticError::inexact};bool inc=false;if(r){switch(m){case Rounding::toward_zero:break;case Rounding::floor:inc=neg;break;case Rounding::ceil:inc=!neg;break;case Rounding::nearest_even:inc=r*2>d||(r*2==d&&((q&1)!=0));break;case Rounding::nearest_away:inc=r*2>=d;break;case Rounding::exact:break;}}if(inc)++q;cpp_int z=neg?-q:q;if(!fits(z,bits))return{false,0,ArithmeticError::overflow};return{true,z,ArithmeticError::overflow};}
struct S{uint64_t checks=0,fail=0;};
template<class F,class E>void chk(const char*op,const O&w,const E&g,S&s,cpp_int a,cpp_int b,cpp_int c,Rounding m,unsigned qd=999){++s.checks;bool bad=w.ok!=g.has_value();if(!bad&&w.ok)bad=w.v!=cv(*g);if(!bad&&!w.ok&&w.e!=g.error())bad=true;if(bad){++s.fail;if(s.fail<=50){std::cerr<<"FAIL "<<op<<" Fixed"<<F::bits<<"<"<<F::fractional_digits<<"> m="<<int(m)<<" qd="<<qd<<" a="<<a<<" b="<<b<<" c="<<c<<" want="<<(w.ok?w.v.convert_to<std::string>():"ERR("+std::to_string(int(w.e))+")")<<" got=";if(g)std::cerr<<cv(*g);else std::cerr<<"ERR("<<int(g.error())<<")";std::cerr<<'\n';}}}
template<class F,class E>void simple(const char*op,cpp_int want,bool ok,const E&g,S&s,cpp_int a,cpp_int b=0){O w{ok,want,ArithmeticError::overflow};chk<F>(op,w,g,s,a,b,0,Rounding::toward_zero);}

template<class F>S audit(uint64_t n,uint64_t seed){S s;std::mt19937_64 rg(seed);const Rounding ms[]={Rounding::toward_zero,Rounding::floor,Rounding::ceil,Rounding::nearest_even,Rounding::nearest_away,Rounding::exact};cpp_int scale=p10(F::fractional_digits);auto test=[&](F a,F b,F c,uint64_t idx){cpp_int x=cv(a),y=cv(b),z=cv(c);simple<F>("add",x+y,fits(x+y,F::bits),add(a,b),s,x,y);simple<F>("sub",x-y,fits(x-y,F::bits),sub(a,b),s,x,y);simple<F>("neg",-x,x!=lo(F::bits),negate(a),s,x);simple<F>("abs",x<0?-x:x,x!=lo(F::bits),abs(a),s,x);if(y==0){O w{false,0,ArithmeticError::division_by_zero};chk<F>("remainder",w,remainder(a,b),s,x,y,z,Rounding::toward_zero);}else{simple<F>("remainder",x%y,true,remainder(a,b),s,x,y);}for(auto m:ms){chk<F>("mul",rq(x*y,scale,m,F::bits),mul(a,b,m),s,x,y,z,m);chk<F>("div",rq(x*scale,y,m,F::bits),div(a,b,m),s,x,y,z,m);chk<F>("mul_div",rq(x*y,z,m,F::bits),mul_div(a,b,c,m),s,x,y,z,m);}unsigned d=F::fractional_digits?unsigned(idx%(F::fractional_digits+1)):0;cpp_int unit=p10(F::fractional_digits-d),mag=x<0?-x:x,q=mag/unit,r=mag%unit;for(auto m:ms){O w;if(r&&m==Rounding::exact)w={false,0,ArithmeticError::inexact};else{bool inc=false;if(r){if(m==Rounding::floor)inc=x<0;else if(m==Rounding::ceil)inc=x>=0;else if(m==Rounding::nearest_away)inc=r*2>=unit;else if(m==Rounding::nearest_even)inc=r*2>unit||(r*2==unit&&((q&1)!=0));}cpp_int qq=q+(inc?1:0),out=(x<0?-qq:qq)*unit;w={fits(out,F::bits),out,ArithmeticError::overflow};}chk<F>("quantize",w,quantize(a,d,m),s,x,y,z,m,d);} };
 F bs[]={F{},raw1<F>(1),raw1<F>(-1),F::min(),F::max()};uint64_t idx=0;for(auto a:bs)for(auto b:bs)for(auto c:bs)test(a,b,c,idx++);for(uint64_t i=0;i<n;++i)test(randv<F>(rg),randv<F>(rg),randv<F>(rg),idx++);return s;}
int main(){S t;auto run=[&](auto f,uint64_t n,uint64_t seed){using F=decltype(f);auto s=audit<F>(n,seed);t.checks+=s.checks;t.fail+=s.fail;std::cout<<"Fixed"<<F::bits<<"<"<<F::fractional_digits<<"> checks="<<s.checks<<" failures="<<s.fail<<'\n';};run(Fixed8<2>{},20000,1);run(Fixed16<4>{},25000,2);run(Fixed32<9>{},30000,3);run(Fixed64<12>{},30000,4);run(Fixed128<12>{},20000,5);run(Fixed128<38>{},10000,6);run(Fixed256<18>{},5000,7);run(Fixed256<76>{},2000,8);std::cout<<"TOTAL checks="<<t.checks<<" failures="<<t.fail<<'\n';return t.fail?1:0;}
