#include <fixedwide/all.hpp>
#include <boost/multiprecision/cpp_int.hpp>
#include <bit>
#include <cstdint>
#include <iostream>
#include <random>
using namespace fixedwide; using boost::multiprecision::cpp_int;
static cpp_int p10(unsigned d){cpp_int x=1;while(d--)x*=10;return x;}
template<class F>cpp_int cv(F f){if constexpr(F::bits<=64)return cpp_int(f.raw());else if constexpr(F::bits==128){auto r=f.raw();cpp_int x=(cpp_int(r.high)<<64)|r.low;if(r.high>>63)x-=(cpp_int(1)<<128);return x;}else{auto r=f.raw();cpp_int x=0;for(int i=3;i>=0;--i)x=(x<<64)|r.limbs[i];if(r.limbs[3]>>63)x-=(cpp_int(1)<<256);return x;}}
template<class F>F rv(std::mt19937_64&g){if constexpr(F::bits==8)return F::from_raw(std::bit_cast<int8_t>(uint8_t(g())));else if constexpr(F::bits==16)return F::from_raw(std::bit_cast<int16_t>(uint16_t(g())));else if constexpr(F::bits==32)return F::from_raw(std::bit_cast<int32_t>(uint32_t(g())));else if constexpr(F::bits==64)return F::from_raw(std::bit_cast<int64_t>(g()));else if constexpr(F::bits==128)return F::from_raw(wide::int128(g(),g()));else return F::from_raw(wide::int256(g(),g(),g(),g()));}
template<class F>F raw1(int v){if constexpr(F::bits<=64)return F::from_raw(static_cast<typename F::raw_type>(v));else if constexpr(F::bits==128)return F::from_raw(wide::int128(v));else return F::from_raw(wide::int256(v));}
struct O{bool ok;cpp_int v;ArithmeticError e;};struct S{uint64_t n=0,f=0;};
static O rq(cpp_int n,cpp_int d,Rounding m,unsigned bits){if(d==0)return{false,0,ArithmeticError::division_by_zero};bool neg=(n<0)!=(d<0);if(n<0)n=-n;if(d<0)d=-d;cpp_int q=n/d,r=n%d;if(r&&m==Rounding::exact)return{false,0,ArithmeticError::inexact};bool inc=false;if(r){if(m==Rounding::floor)inc=neg;else if(m==Rounding::ceil)inc=!neg;else if(m==Rounding::nearest_away)inc=r*2>=d;else if(m==Rounding::nearest_even)inc=r*2>d||(r*2==d&&((q&1)!=0));}if(inc)++q;cpp_int z=neg?-q:q,lo=-(cpp_int(1)<<(bits-1)),hi=(cpp_int(1)<<(bits-1))-1;if(z<lo||z>hi)return{false,0,ArithmeticError::overflow};return{true,z,ArithmeticError::overflow};}
template<class D,class E>void ck(const char*op,const O&w,const E&g,S&s,cpp_int a,cpp_int b,cpp_int c,Rounding m){++s.n;bool bad=w.ok!=g.has_value();if(!bad&&w.ok)bad=w.v!=cv(*g);if(!bad&&!w.ok&&w.e!=g.error()){if(!((w.e==ArithmeticError::overflow&&g.error()==ArithmeticError::inexact)||(w.e==ArithmeticError::inexact&&g.error()==ArithmeticError::overflow)))bad=true;}if(bad){++s.f;if(s.f<=40){std::cerr<<"FAIL "<<op<<" -> Fixed"<<D::bits<<"<"<<D::fractional_digits<<"> m="<<int(m)<<" a="<<a<<" b="<<b<<" c="<<c<<" want="<<(w.ok?w.v.convert_to<std::string>():"ERR("+std::to_string(int(w.e))+")")<<" got=";if(g)std::cerr<<cv(*g);else std::cerr<<"ERR("<<int(g.error())<<")";std::cerr<<'\n';}}}
template<class A,class B,class C,class D>S run(uint64_t n,uint64_t seed){S s;std::mt19937_64 rg(seed);const Rounding ms[]={Rounding::toward_zero,Rounding::floor,Rounding::ceil,Rounding::nearest_even,Rounding::nearest_away,Rounding::exact};auto test=[&](A a,B b,C c){cpp_int x=cv(a),y=cv(b),z=cv(c),sa=p10(A::fractional_digits),sb=p10(B::fractional_digits),sc=p10(C::fractional_digits),sd=p10(D::fractional_digits);++s.n;cpp_int l=x*sb,r=y*sa;if((a==b)!=(l==r)||(a<b)!=(l<r)||(a>b)!=(l>r)){++s.f;if(s.f<=40)std::cerr<<"FAIL compare a="<<x<<" b="<<y<<'\n';}for(auto m:ms){ck<D>("cast",rq(x*sd,sa,m,D::bits),fixed_cast<D>(a,m),s,x,y,z,m);ck<D>("add_to",rq((x*sb+y*sa)*sd,sa*sb,m,D::bits),add_to<D>(a,b,m),s,x,y,z,m);ck<D>("sub_to",rq((x*sb-y*sa)*sd,sa*sb,m,D::bits),sub_to<D>(a,b,m),s,x,y,z,m);ck<D>("mul_to",rq(x*y*sd,sa*sb,m,D::bits),mul_to<D>(a,b,m),s,x,y,z,m);ck<D>("div_to",rq(x*sb*sd,y*sa,m,D::bits),div_to<D>(a,b,m),s,x,y,z,m);ck<D>("mul_div_to",rq(x*y*sc*sd,z*sa*sb,m,D::bits),mul_div_to<D>(a,b,c,m),s,x,y,z,m);}};A as[]={A{},raw1<A>(1),raw1<A>(-1),A::min(),A::max()};B bs[]={B{},raw1<B>(1),raw1<B>(-1),B::min(),B::max()};C cs[]={C{},raw1<C>(1),raw1<C>(-1),C::min(),C::max()};for(auto a:as)for(auto b:bs)for(auto c:cs)test(a,b,c);for(uint64_t i=0;i<n;++i)test(rv<A>(rg),rv<B>(rg),rv<C>(rg));return s;}
int main(){S t;auto go=[&]<class A,class B,class C,class D>(const char*name,uint64_t n,uint64_t seed){auto s=run<A,B,C,D>(n,seed);t.n+=s.n;t.f+=s.f;std::cout<<name<<" checks="<<s.n<<" failures="<<s.f<<'\n';};go.template operator()<Fixed32<4>,Fixed64<8>,Fixed16<2>,Fixed128<12>>("small_to_128",8000,1);go.template operator()<Fixed64<12>,Fixed32<4>,Fixed64<8>,Fixed64<8>>("mixed_to_64",8000,2);go.template operator()<Fixed128<38>,Fixed256<76>,Fixed128<0>,Fixed256<76>>("wide_to_256",2500,3);go.template operator()<Fixed256<0>,Fixed256<76>,Fixed256<76>,Fixed256<76>>("worst_div_scale",1000,4);go.template operator()<Fixed256<76>,Fixed256<76>,Fixed256<0>,Fixed256<76>>("worst_muldiv_scale",1000,5);go.template operator()<Fixed256<76>,Fixed128<38>,Fixed64<18>,Fixed8<2>>("wide_to_small",2500,6);go.template operator()<Fixed128<0>,Fixed128<0>,Fixed128<0>,Fixed128<0>>("min128",2500,7);go.template operator()<Fixed256<0>,Fixed256<0>,Fixed256<0>,Fixed256<0>>("min256",1000,8);std::cout<<"TOTAL checks="<<t.n<<" failures="<<t.f<<'\n';return t.f?1:0;}
