#!/usr/bin/env bash
# Regenerate MANIFEST.sha256 from what git actually tracks.
#
# The previous manifest had twelve mismatches and five missing entries because
# it hashed a working tree that contained stale build artefacts. Hashing the
# tracked file list makes it reproducible from a clean checkout by definition.
set -euo pipefail
SRC=$(cd "$(dirname "$0")/.." && pwd)
cd "$SRC"
{
    echo "# fixedwide $(sed -n 's/.*FIXEDWIDE_VERSION_STRING "\(.*\)"/\1/p' include/fixedwide/version.hpp)"
    echo "# generated by scripts/make_manifest.sh from git-tracked files"
    echo "# verify with: sha256sum -c MANIFEST.sha256"
    # Excluded: the manifest itself, and the two files that are produced FROM
    # the finished archive (its checksum, and the log of extracting and testing
    # it). Those cannot be inside the thing they describe.
    git ls-files -z \
        | grep -zv -e '^MANIFEST.sha256$' -e '^SHA256SUMS$' \
                   -e '^reports/fresh_extraction_verification.log$' \
        | sort -z | xargs -0 sha256sum
} > MANIFEST.sha256
echo "MANIFEST.sha256: $(grep -vc '^#' MANIFEST.sha256) files"
