#!/usr/bin/env bash
# Build a release archive and prove it, without any circular evidence.
#
# The previous version wrote SHA256SUMS and the extraction log into the working
# tree, committed them, and then built the archive from HEAD -- so the archive
# always contained the PREVIOUS release's checksum and the PREVIOUS release's
# verification log, describing a different archive. It also swallowed manifest
# failures with `|| true` and only counted them.
#
# This version keeps generated evidence OUT of the archive:
#
#   1. export the tracked tree into a staging directory
#   2. generate MANIFEST.sha256 inside staging, from what is actually there
#   3. zip staging
#   4. checksum and verify the zip from outside it
#   5. build and test a fresh extraction of the zip
#
# The three release assets are the zip, its .sha256, and the verification log.
# None of them is inside the zip, so nothing describes itself.
set -euo pipefail

SRC=$(cd "$(dirname "$0")/.." && pwd)
cd "$SRC"

VERSION=$(sed -n 's/.*FIXEDWIDE_VERSION_STRING "\(.*\)"/\1/p' include/fixedwide/version.hpp)
PREFIX="fixedwide-${VERSION}"
OUT=${OUT:-$SRC/dist}
ZIP="$OUT/${PREFIX}-source.zip"
LOG="$OUT/${PREFIX}-verification.log"

if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "refusing to build a release archive from a dirty tree" >&2
    exit 1
fi

rm -rf "$OUT"
mkdir -p "$OUT"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
STAGE="$WORK/$PREFIX"

# 1. Exactly what is committed, nothing from the working tree.
mkdir -p "$STAGE"
git archive HEAD | tar -x -C "$STAGE"

# 2. The manifest describes the staged tree, and is generated from it. It cannot
#    be stale by construction, which is what kept going wrong when it was a
#    tracked file that every unrelated merge invalidated.
(
    cd "$STAGE"
    {
        echo "# fixedwide $VERSION"
        echo "# generated by scripts/release.sh from the staged archive contents"
        echo "# verify with: sha256sum -c MANIFEST.sha256"
        find . -type f ! -name MANIFEST.sha256 -print0 | sort -z \
            | xargs -0 sha256sum | sed 's| \./| |'
    } > MANIFEST.sha256
)
echo "staged $(grep -vc '^#' "$STAGE/MANIFEST.sha256") files"

# 3. Zip the staged tree.
( cd "$WORK" && zip -qr "$ZIP" "$PREFIX" )
sha256sum "$ZIP" | sed "s|$OUT/||" > "$ZIP.sha256"

# 4/5. Verify from outside, and fail loudly. Every check below is fatal: the
#      previous script recorded failures into the log and carried on.
EXTRACT="$WORK/extract"
mkdir -p "$EXTRACT"
{
    echo "# fixedwide release verification"
    echo "date:    $(date -Is)"
    echo "version: $VERSION"
    echo "commit:  $(git rev-parse HEAD)"
    echo "archive: $(basename "$ZIP")"
    echo "sha256:  $(cut -d' ' -f1 "$ZIP.sha256")"
    echo
    echo "## archive integrity"
} > "$LOG"

unzip -tq "$ZIP" >> "$LOG" 2>&1
echo "unzip -t: no errors in compressed data" >> "$LOG"

unzip -q "$ZIP" -d "$EXTRACT"
tree="$EXTRACT/$PREFIX"

echo >> "$LOG"
echo "## manifest verification inside the extracted tree" >> "$LOG"
if ( cd "$tree" && sha256sum -c --quiet MANIFEST.sha256 ) >> "$LOG" 2>&1; then
    echo "$(grep -vc '^#' "$tree/MANIFEST.sha256") files verified, 0 failures" >> "$LOG"
else
    echo "MANIFEST VERIFICATION FAILED inside the extracted archive" | tee -a "$LOG" >&2
    exit 1
fi

echo >> "$LOG"
echo "## build and test from the extracted archive" >> "$LOG"
cmake -S "$tree" -B "$EXTRACT/build" -G Ninja \
      -DCMAKE_BUILD_TYPE=Release \
      -DFIXEDWIDE_BUILD_TESTS=ON -DFIXEDWIDE_BUILD_EXAMPLES=ON >> "$LOG" 2>&1
cmake --build "$EXTRACT/build" -j"$(nproc)" >> "$LOG" 2>&1
ctest --test-dir "$EXTRACT/build" --output-on-failure >> "$LOG" 2>&1
RESULT=$(grep -E "tests passed" "$LOG" | tail -1)
echo "RESULT: $RESULT" >> "$LOG"

echo
echo "release assets in $OUT:"
ls -1 "$OUT" | sed 's/^/  /'
echo
echo "$RESULT"
